# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Anbindung der Ledatronic LT3 WIFI'
        en: 'Pluign to connect to Ledatronic LT3'
    maintainer: sisamiwe
#    tester:                         # Who tests this plugin?
    state: develop                  # Initial 'develop'. change to 'ready' when done with development
#    keywords: iot xyz
#    documentation: ''              # An url to optional plugin doc - NOT the url to user_doc!!!
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)

    # these min/max-versions MUST be given in quotes, or e.g. 3.10 will be interpreted as 3.1 (3.1 < 3.9 < 3.10)
    sh_minversion: '1.10'           # minimum shNG version to use this plugin
#    sh_maxversion: '1.11'          # maximum shNG version to use this plugin (omit if latest)
#    py_minversion: '3.10'          # minimum Python version to use for this plugin
#    py_maxversion: '4.25'          # maximum Python version to use for this plugin (omit if latest)

    multi_instance: false           # plugin supports multi instance
    restartable: unknown            # plugin supports stopping and starting again, must be implemented
    #configuration_needed: False    # False: The plugin will be enabled by the Admin GUI without configuration
    classname: Ledatronic           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

    pause_item:
        type: str
        default: ''
        description:
            de: 'Item, um die Ausführung des Plugins zu steuern'
            en: 'item for controlling plugin execution'

    host:
        type: str
        mandatory: true
        description:
            de: 'Hostname oder IP-Adresse der Ledatronic'
            en: 'host name or IP-address of Ledatronic'

    port:
        type: int
        default: 10001
        description:
            de: 'Port der Ledatronic'
            en: 'Port of Ledatronic'

    cycle:
        type: int
        default: 10
        description:
            de: 'Abfragezyklus'
            en: 'poll cycle'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

    leda_data_point:
        type: str
        mandatory: true
        description:
            de: Ledatronic Datenpunkt für das jeweiligen Items.
            en: Ledatronic data point for the respective item.
        valid_list:
            - current_combustion_temp   # num
            - active    # bool
            - max_combustion_temp   # num
            - base_glow_temp   # num
            - trend   # num
            - num_burn_cycles   # num
            - num_heating_errors   # num
            - oven_state_mapped    # str
            - air_flap_setpoint   # num
            - air_flap_actual   # num
            - controller_version   # num

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    abbrand:
        ofen_an:
            type: bool
            visu_acl: ro
            leda_data_point@instance: active
        ofen_status:
            type: str
            visu_acl: ro
            leda_data_point@instance: oven_state_mapped
        brennraumtemp:
            type: num
            remark: unit °C
            visu_acl: ro
            leda_data_point@instance: current_combustion_temp
        brennraumtemp_max:
            type: num
            visu_acl: ro
            leda_data_point@instance: max_combustion_temp
        grundgluttemp:
            type: num
            visu_acl: ro
            leda_data_point@instance: base_glow_temp
        abbrandkurventrend:
            type: num
            visu_acl: ro
            leda_data_point@instance: trend
        zuluftklappenstellung_soll:
            type: num
            visu_acl: ro
            leda_data_point@instance: air_flap_setpoint
        zuluftklappenstellung_ist:
            type: num
            visu_acl: ro
            leda_data_point@instance: air_flap_actual
        anzahl_abbraende:
            type: num
            visu_acl: ro
            leda_data_point@instance: num_burn_cycles
        anzahl_heizfehler:
            type: num
            visu_acl: ro
            leda_data_point@instance: num_heating_errors
        regler_version:
            type: num
            visu_acl: ro
            leda_data_point@instance: controller_version

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
